### ISSUE TITLE
Wheel support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [zopefoundation/zope.interface#214]
**Summary**
Installing zope-interface on aarch64 via pip using command "pip3 install zope-interface" tries to build wheel from source code

**Problem description**
zope-interface doesn't have wheel for aarch64 on PyPI repository. So, while installing zope-interface via pip on aarch64, pip builds wheel for same resulting in it takes more time to install zope-interface. Making wheel available for aarch64 will benefit aarch64 users by minimizing zope-interface installation time.

**Expected Output**
Pip should be able to download zope-interface wheel from PyPI repository rather than building it from source code.

@zope-interface-taem, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make zope-interface wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by jamadden** [comment]
In theory this is relatively easy to do on Travis with the proper docker setup in our .travis.yml, something like:

```yaml
       name: aarch64 wheels
       group: edge
       arch: arm64
       virt: lxd
       env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_aarch64
       install: docker pull $DOCKER_IMAGE
       script: bash .manylinux.sh
```

I wouldn't want to do that unless we also changed the '.manylinux-install.sh' script to actively run the test suite on each version of Python. I don't like the idea of publishing wheels for platforms that have never been tested.
